name: Terraform OCI Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Create OCI private key file
        run: |
          echo "${{ secrets.PRIVATEKEY }}" > APIPrivateKey.pem
          chmod 600 APIPrivateKey.pem
      
      - name: Install OCI CLI
        run: |
          pip install oci-cli

      - name: Ensure Terraform State Bucket Exists
        run: |
          BUCKET_NAME="terraform-state"
          NAMESPACE="${{ secrets.OCI_NAMESPACE }}"
          COMPARTMENT_ID="${{ secrets.COMPARTMENT_OCID }}"

          echo "Checking if bucket $BUCKET_NAME exists..."

          EXISTS=$(oci os bucket list \
            --namespace $NAMESPACE \
            --compartment-id $COMPARTMENT_ID \
            --query "data[?name=='$BUCKET_NAME'] | length(@)" \
            --raw-output)

          if [ "$EXISTS" -eq 0 ]; then
            echo "Bucket not found. Creating bucket: $BUCKET_NAME"
            oci os bucket create \
              --namespace $NAMESPACE \
              --compartment-id $COMPARTMENT_ID \
              --name $BUCKET_NAME
          else
            echo "Bucket already exists."
          fi


      
      
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate


      - name: Terraform Plan
        run: |
          terraform plan \
            -var "tenancyocid=${{ secrets.TENANCYOCID }}" \
            -var "userocid=${{ secrets.USEROCID }}" \
            -var "finger_print=${{ secrets.FINGER_PRINT }}" \
            -var "privatekeypath=APIPrivateKey.pem"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          # terraform apply -auto-approve \
            -var "tenancyocid=${{ secrets.TENANCYOCID }}" \
            -var "userocid=${{ secrets.USEROCID }}" \
            -var "finger_print=${{ secrets.FINGER_PRINT }}" \
            -var "privatekeypath=APIPrivateKey.pem"

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve 

