name: Terraform OCI Yaml
on: 
 workflow_dispatch:
 jobs:
   terraform:
     runs-on: ubuntu-latest

     steps:
       - name: checkout repository_dispatch
         uses: actions/checkout@v3
       - name: Set up terraform
         uses: hashicorp/setup-terraform@v2
       - name: Create OCI private key file
         run: |
               echo "${{secrets.PRIVATEKEY}}" >> APIPrivateKey.pem
               chomd 600 APIPrivateKey.pem
       - name: Terraform Init
         run: terraform init
       - name: Terraform Plan
        run: terraform plan \
          -var "tenancyocid=${{ secrets.TENANCYOCID }}" \
          -var "userocid=${{ secrets.USEROCID }}" \
          -var "finger_print=${{ secrets.FINGER_PRINT }}" \
          -var "private_key_path=APIPrivateKey.pem" \
          
