name: Terraform OCI Yaml
on: 
 workflow_dispatch:
 jobs:
   terraform:
     runs-on: ubuntu-latest

     steps:
       - name: checkout repository_dispatch
         checkout: actions/checkout@v3
       
